Update generate.yml

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -34,7 +34,23 @@ jobs:
         bash ../scripts/sign_commit
         mkdir dist && cd dist
         mkdir vectras
-        ./configure --target-list=x86_64-softmmu --cross-prefix=aarch64-linux-gnu- --enable-cross-prefix --enable-cross-compile --enable-spice --disable-kvm --enable-tcg --disable-virtfs --disable-vnc --disable-libiscsi --audio-drv-list=pa
+        # The configure script should be in this directory. Check that it's there
+        if [ -f configure ]; then
+          chmod +x configure
+          ./configure 
+            --cross-prefix=aarch64-linux-gnu- 
+            --target-list=aarch64-softmmu 
+            --enable-spice 
+            --disable-kvm 
+            --enable-tcg 
+            --enable-virtfs 
+            --enable-vnc 
+            --enable-libiscsi 
+            --audio-drv-list=pa
+        else
+          echo "Configure script not found"
+          exit 1
+        fi        
         make -j$(nproc)
         make install DESTDIR=../dist/vectras
 
